### ISSUE TITLE
s2gkg的准确率低于s2g

### ISSUE THREAD

**Issue by RingoTC** [DoubleBite/Sequence-to-General-tree#2]
我执行了run_s2g.sh和run_s2gkg.sh两个文件，得到结果
run_s2g.sh 54.08% (756/1398)
run_s2gkg.sh 53.93% (754/1398)

请问源码中给出的超参是论文中使用的超参吗？还是说其他地方存在一定差异？

**Comment by ICanFlyGFC** [comment]
您好，可以分享下requirements.txt吗？谢谢。
